---
title: Sprocket Plate
category: Complex Shapes
description: Gear-like plate with polar tooth generation, bolt circle arrays, and radial dimensions.
---

import ExampleTabs from "@examples/components/ExampleTabs.svelte";
import SprocketPlate from "./SprocketPlate.svelte";

<ExampleTabs>
  <SprocketPlate client:visible slot="scene" />
  <Fragment slot="code">
```typescript
import { Pluton2D } from "pluton-2d";

type SceneParams = {
  outerRadius: number;
  toothCount: number;
  toothDepth: number;
  boreRadius: number;
  boltCircleRadius: number;
  boltCount: number;
  boltHoleDiameter: number;
};

const svgElement = document.querySelector("svg#sprocket") as SVGSVGElement;
const scene = new Pluton2D<SceneParams>(svgElement, {
  outerRadius: 188,
  toothCount: 22,
  toothDepth: 20,
  boreRadius: 36,
  boltCircleRadius: 84,
  boltCount: 6,
  boltHoleDiameter: 14,
});

const geometry = scene.geometry.group();
const dimensions = scene.dimensions.group();

const plateFillId = scene.addHatchFill("#0f766e", 0.18);
const boltFillId = scene.addHatchFill("#7f1d1d", 0.16);
const CIRCLE_HANDLE_FACTOR = 0.5522847498;

const appendCircle = (path: any, centerX: number, centerY: number, radiusValue: number) => {
  const handleOffset = radiusValue * CIRCLE_HANDLE_FACTOR;
  path
    .moveToAbs(centerX - radiusValue, centerY)
    .cubicToAbs(
      centerX - radiusValue,
      centerY + handleOffset,
      centerX - handleOffset,
      centerY + radiusValue,
      centerX,
      centerY + radiusValue,
    )
    .smoothCubicToAbs(centerX + radiusValue, centerY + handleOffset, centerX + radiusValue, centerY)
    .smoothCubicToAbs(centerX + handleOffset, centerY - radiusValue, centerX, centerY - radiusValue)
    .smoothCubicToAbs(centerX - radiusValue, centerY - handleOffset, centerX - radiusValue, centerY)
    .close();
};

scene.draw((params) => {
  const toothCountValue = Math.max(10, Math.round(params.toothCount));
  const rootRadiusValue = Math.min(
    params.outerRadius - 8,
    Math.max(params.boreRadius + params.boltHoleDiameter * 1.3, params.outerRadius - params.toothDepth),
  );

  const profilePoints: Array<{ x: number; y: number }> = [];
  for (let index = 0; index < toothCountValue * 2; index++) {
    const angle = -Math.PI / 2 + (index * Math.PI) / toothCountValue;
    const radiusValue = index % 2 === 0 ? params.outerRadius : rootRadiusValue;
    profilePoints.push({ x: Math.cos(angle) * radiusValue, y: Math.sin(angle) * radiusValue });
  }

  const platePath = geometry.path({ className: "demo-sprocket-plate", fill: plateFillId });
  platePath.moveToAbs(profilePoints[0].x, profilePoints[0].y);
  for (let index = 1; index < profilePoints.length; index++) platePath.lineToAbs(profilePoints[index].x, profilePoints[index].y);
  platePath.close();

  const boltPath = geometry.path({ className: "demo-sprocket-bolts", fill: boltFillId });
  const holeCount = Math.max(3, Math.round(params.boltCount));
  const holeRadius = params.boltHoleDiameter / 2;
  for (let index = 0; index < holeCount; index++) {
    const angle = (index / holeCount) * Math.PI * 2;
    const centerX = Math.cos(angle) * params.boltCircleRadius;
    const centerY = Math.sin(angle) * params.boltCircleRadius;
    appendCircle(boltPath, centerX, centerY, holeRadius);
  }

  const dimensionPath = dimensions.dimension({ className: "sprocket-dim" });
  dimensionPath.moveToAbs(-params.outerRadius, params.outerRadius + 34).lineTo(params.outerRadius * 2, 0);
});
```
  </Fragment>
</ExampleTabs>
