---
title: Welded End Plate Connection
category: Draft
description: Beam to support end plate connection with bolt grid, weld symbols, and dual-view dimensions.
---

import ExampleTabs from "@examples/components/ExampleTabs.svelte";
import WeldedEndPlate from "./WeldedEndPlate.svelte";

<ExampleTabs>
  <WeldedEndPlate client:visible slot="scene" />
  <Fragment slot="code">
```typescript
import { Pluton2D } from "pluton-2d";

type SceneParams = {
  beamDepth: number;
  flangeWidth: number;
  plateThickness: number;
  boltRows: number;
  boltPitch: number;
  boltGauge: number;
  boltDiameter: number;
  edgeDistance: number;
  weldSize: number;
};

const svgElement = document.querySelector("svg#welded-end-plate") as SVGSVGElement;
const scene = new Pluton2D(svgElement, {
  params: {
    beamDepth: 240,
    flangeWidth: 160,
    plateThickness: 20,
    boltRows: 4,
    boltPitch: 58,
    boltGauge: 92,
    boltDiameter: 20,
    edgeDistance: 34,
    weldSize: 10,
  }
});

const geometry = scene.geometry.group();
const dimensions = scene.dimensions.group();

const steelFillId = scene.addHatchFill("#0f766e", 0.14);
const plateFillId = scene.addHatchFill("#334155", 0.18);
const boltFillId = scene.addHatchFill("#7f1d1d", 0.15);
const CIRCLE_HANDLE_FACTOR = 0.5522847498;

const appendCircle = (path: any, centerX: number, centerY: number, radiusValue: number) => {
  const handleOffset = radiusValue * CIRCLE_HANDLE_FACTOR;
  path
    .moveToAbs(centerX - radiusValue, centerY)
    .cubicToAbs(
      centerX - radiusValue,
      centerY + handleOffset,
      centerX - handleOffset,
      centerY + radiusValue,
      centerX,
      centerY + radiusValue,
    )
    .smoothCubicToAbs(centerX + radiusValue, centerY + handleOffset, centerX + radiusValue, centerY)
    .smoothCubicToAbs(centerX + handleOffset, centerY - radiusValue, centerX, centerY - radiusValue)
    .smoothCubicToAbs(centerX - radiusValue, centerY - handleOffset, centerX - radiusValue, centerY)
    .close();
};

scene.draw((params) => {
  const boltRowCount = Math.max(2, Math.round(params.boltRows));
  const plateHeight = Math.max(
    params.beamDepth + 86,
    2 * params.edgeDistance + (boltRowCount - 1) * params.boltPitch + params.boltDiameter + 16,
  );

  const beamPath = geometry.path({ className: "demo-weld-beam", fill: steelFillId });
  const platePath = geometry.path({ className: "demo-weld-plate", fill: plateFillId });
  const boltPath = geometry.path({ className: "demo-weld-bolts", fill: boltFillId });

  beamPath
    .moveToAbs(-380, params.beamDepth / 2)
    .lineToAbs(-170, params.beamDepth / 2)
    .moveToAbs(-380, -params.beamDepth / 2)
    .lineToAbs(-170, -params.beamDepth / 2);

  platePath
    .moveToAbs(-170, -plateHeight / 2)
    .lineToAbs(-170 + params.plateThickness, -plateHeight / 2)
    .lineToAbs(-170 + params.plateThickness, plateHeight / 2)
    .lineToAbs(-170, plateHeight / 2)
    .close();

  const boltRadius = params.boltDiameter / 2;
  for (let index = 0; index < boltRowCount; index++) {
    const boltY = plateHeight / 2 - params.edgeDistance - index * params.boltPitch;
    appendCircle(boltPath, -170 + params.plateThickness / 2, boltY, boltRadius);
  }

  const dimensionPath = dimensions.dimension({ className: "weld-dim" });
  dimensionPath.moveToAbs(-416, -params.beamDepth / 2).lineTo(0, params.beamDepth);
});
```
  </Fragment>
</ExampleTabs>
